name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check file structure
        run: |
          echo "Checking repository structure..."
          ls -la prompts/
          ls -la templates/
          echo "Structure validation passed"